# Generated by Django 3.2.9 on 2021-11-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Commnent',
        ),
    ]
